[phases.setup]
nixPkgs = ["python311", "ffmpeg"]

[phases.install]
cmds = ["python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"]
cacheDirectories = ["/root/.cache/pip", "/var/cache/apt"]

[start]
cmd = "python bot.py"
